### ISSUE TITLE
Adding for loop to LimnoSat Pulls for Fire data

### ISSUE THREAD

**Issue by mishafredmeyer** [rossyndicate/aquasat_v2#1]
For the fire code, we were hoping to loop through all of the states for which @SimonTopp calculated Deepest Points. I think that this is all lakes in the NHD with the exception of Texas (which errored out for a bizarre reason).... 

Simon -- 
1. I know that you created a `for loop` to iterate through each of the states for which we have Deepest Points. I just don't know where to put that for loop in the code... Could you please look at the script [`2_rsdata/src/LakeExport.py`](https://github.com/rossyndicate/aquasat_v2/blob/main/2_rsdata/src/LakeExport.py) and insert the for loop?
2. I also don't know which NHD version/dataset you used to calculate Deepest Points. Was this NHD or NHDPlus? The unique identifiers seemed a little wonky when @bellaoleksy was joining them. 

@bellaoleksy -- feel free to add in extra detail if I mischaracterized anything!

**Comment by SimonTopp** [comment]
I should be able to get to this tomorrow, but for now I used the NHD hosted by awesome community datasets (https://gee-community-catalog.org/projects/nhd/).  Pretty sure it's just plain old NHD and not NHDPlus. Unique ids are are from the `Permanent_Identifier` column.

**Comment by mishafredmeyer** [comment]
okay....seems to work for Alabama.... but errors out when we get to Arkansas... 

`EEException: Collection.loadTable: Collection asset 'users/sntopp/NHD/DeepestPoint/NHD_AR' not found.`
